name: Checks

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn sdk:build
      - run: yarn tsc
      - run: yarn lint --quiet

  build:
    name: Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn install
          rm -rf ./app/public/images
          yarn app:build:static
        env:
          BUILD_INFURA_PROJECT_ID: ${{ secrets.BUILD_INFURA_PROJECT_ID }}
          BUILD_ALCHEMY_PROJECT_ID: ${{ secrets.BUILD_ALCHEMY_PROJECT_ID }}
          NEXT_PUBLIC_IPFS: true
          NEXT_PUBLIC_RELEASE_TAG: ${{ needs.tag.outputs.new_tag }}
