name: Release

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    if: ${{ github.repository == 'lyra-finance/interface' }}
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}
      changelog: ${{ steps.github-tag-action.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump and tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          default_bump: patch

  release:
    needs: tag
    if: |
      ${{ needs.tag.outputs.new_tag != null }} &&
      ${{ github.repository == 'lyra-finance/interface' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: |
          rm -rf ./app/public/images
          yarn app:build:static
        env:
          BUILD_INFURA_PROJECT_ID: ${{ secrets.BUILD_INFURA_PROJECT_ID }}
          NEXT_PUBLIC_IPFS: true
          NEXT_PUBLIC_RELEASE_TAG: ${{ needs.tag.outputs.new_tag }}

      - name: Pin to IPFS
        id: pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@39bbda1ce1fe24c69c6f57861b8038278d53688d
        with:
          pin-name: ${{ needs.tag.outputs.new_tag }}
          path: "./app/out"
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - uses: lyra-finance/cloudflare-update-action@44509842e05b85fd768bf372282520d1c4a83055
        with:
          CF_API_TOKEN: "${{ secrets.CLOUDFLARE_TOKEN }}"
          CF_ZONE_ID: "${{ secrets.CLOUDFLARE_ZONE_ID }}"
          HASH: "${{ steps.pinata.outputs.hash }}"
          CF_DEPLOYMENT_DOMAIN: ipfs-app.lyra.finance

      - name: Release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          release_name: Release ${{ needs.tag.outputs.new_tag }}
          body: |
            IPFS hash of the deployment: `${{ steps.pinata.outputs.hash }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.lyra.finance](https://app.lyra.finance).
            You can also access the Lyra Interface directly from an IPFS gateway.
            **BEWARE**: The interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.lyra.finance](https://app.lyra.finance).
            Your Lyra settings are never remembered across different URLs.
            ${{ needs.tag.outputs.changelog }}
