name: Sync

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  private-to-public:
    if: ${{ github.repository == 'lyra-finance/interface-private' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote add interface "https://lyra-finance:${GH_PERSONAL_ACCESS_TOKEN}@github.com/lyra-finance/interface.git"
          git push --set-upstream interface master

  public-to-private:
    if: ${{ github.repository == 'lyra-finance/interface' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - run: |
          git config --global user.email "dappbeast"
          git config --global user.name "dappbeast@users.noreply.github.com"
          git remote add interface-private "https://lyra-finance:${GH_PERSONAL_ACCESS_TOKEN}@github.com/lyra-finance/interface-private.git"
          git push --set-upstream interface-private master
